### PR TITLE
github: Split Android CI to per ABI builds

### PR DESCRIPTION
**Pull request by poweifeng**
- Pulled the android continuous workflow into an action
 - Split the android continuous build into 3 ABIs armv7, armv8a,
   and x86_64 (note that x86 is not present).
 - Remove the upload artifacts step from previous workflow.
   Unclear why that was present.
 - Split the android continous into debug build and a release
   build commands, enabling deletion of intermediate output
   directory.

### CODE REVIEW

**Comment by poweifeng** [comment]
Please don't review yet, I'm running this to get the workflows to run on presubmit as a test.

**Comment by poweifeng** [comment]
> Please don't review yet, I'm running this to get the workflows to run on presubmit as a test.

Now ready for review

**Comment by pixelflinger** [comment]
can you add a detailed description of what this does? and/or link to bug in buganizer with the details. thanks!

**Comment by poweifeng** [comment]
> can you add a detailed description of what this does? and/or link to bug in buganizer with the details. thanks!

Done. Description was in the commit, but not sure why it didn't make it to the PR description.

**Review by bejado — APPROVED** [review]

**Comment by bejado** [comment]
> Remove the upload artifacts step from previous workflow. Unclear why that was present.

This was to allow clients to use continuous builds:

https://github.com/google/filament/blob/cdb539b3cf13774c0deb9a091ed734e72bf78a7d/README.md?plain=1#L57-L65

I'm fine with getting rid of these if it makes our GitHub Action code easier to mantain. But we should also probably remove this section from our readme.

**Comment by poweifeng** [comment]
> > Remove the upload artifacts step from previous workflow. Unclear why that was present.
> 
> This was to allow clients to use continuous builds:
> 
> https://github.com/google/filament/blob/cdb539b3cf13774c0deb9a091ed734e72bf78a7d/README.md?plain=1#L57-L65
> 
> I'm fine with getting rid of these if it makes our GitHub Action code easier to maintain. But we should also probably remove this section from our readme.

I see.  Thanks for the background.  Yeah, I'm going to remove them for now and we can revisit later.  (Because a typical `.aar` will need all abis I think, which is not possible with how I'm splitting them).

**Pull request merged**
