### PR TITLE
gltfio: disable shader optimizations by default

### PR DESCRIPTION
**Pull request by prideout**

### CODE REVIEW

**Comment by prideout** [comment]
Note that ubershaders (which are always used on Android and WebGL) are still optimized by default.

**Review by romainguy — APPROVED** [review]
Could you also update the Java API please?

**Comment by romainguy** [comment]
Thanks Philip! I started looking at multithreading filamat, it seems doable, I just need to cleanup some of our code first (we use class members as "globals" between methods, gross).

**Comment by romainguy** [comment]
Oh and you should update RELEASE_NOTES so devs are aware of this change.

**Comment by prideout** [comment]
> Could you also update the Java API please?

The Java API is hardcoded to use ubershaders, I think I was trying to avoid a filamat dependency there.

**Comment by prideout** [comment]
> Oh and you should update RELEASE_NOTES so devs are aware of this change.

Done.

**Comment by romainguy** [comment]
> > Could you also update the Java API please?
> 
> The Java API is hardcoded to use ubershaders, I think I was trying to avoid a filamat dependency there.

Ah right we never created gltfio-lite and gltfio-full. Übershaders come with limitations unfortunately, so ideally we'd want a version of gltfio without spirvopt/cross dependencies but shader generation. That's a problem for another day.

**Pull request merged**
