### PR TITLE
fix gltf data skin matrices offset error

### PR DESCRIPTION
**Pull request by iamjinge**
#1405

### CODE REVIEW

**Comment by iamjinge** [comment]
I signed it!

**Comment by prideout** [comment]
@iamjinge it looks like there is an issue with the CLA, can you try signing again?  If it doesn't work I'll just make the fix myself.

**Comment by iamjinge** [comment]
> @iamjinge it looks like there is an issue with the CLA, can you try signing again? If it doesn't work I'll just make the fix myself.

The username and email of this commit are different from my github account. The CLA issue can't be fixed right now.
You can fix the bug and close this pull request.

**Comment by prideout** [comment]
Closed in favor of #1407

**Pull request closed without merging**
