### PR TITLE
raw string

### PR DESCRIPTION
**Pull request by jiapei-nexera**

### CODE REVIEW

**Review by romainguy — COMMENTED** [review]
Can you explain why this is needed?

**Comment by jiapei100** [comment]
1. Without **r**

```console
  bluegl git:(main) ✗ python bluegl-gen.py 
  File "....../filament/libs/bluegl/bluegl-gen.py", line 66
    '''
       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 58-59: truncated \uXXXX escape
```


2. With **r**
```console
➜  bluegl git:(main) ✗ python bluegl-gen.py
Parsing header include/GL/glcorearb.h...
Parsing header include/GL/glext.h...
Found 2574 functions
Generating public header include/bluegl/BlueGL.h...
Generating define header include/bluegl/BlueGLDefines.h...
Generating proxy src/BlueGLCoreLinuxImpl.S...
Generating proxy src/BlueGLCoreLinuxAArch64Impl.S...
Generating proxy src/BlueGLCoreDarwinImpl.S...
Generating proxy src/BlueGLCoreDarwinAArch64Impl.S...
Generating proxy src/BlueGLCoreWindowsImpl.S...
Generating source src/private_BlueGL.h...
```

**Review by romainguy — APPROVED** [review]
Thank you! I confirmed the fix locally.

**Comment by romainguy** [comment]
Actually I fixed it in a different way and regenerated the bluegl bindings. Closing this. Thanks for noticing the issue!

**Pull request closed without merging**
