### PR TITLE
Expose tangent utility to Java / Kotlin.

### PR DESCRIPTION
**Pull request by prideout**
I did not test this but the JNI binding seem fairly straightforward.

#695

### CODE REVIEW

**Comment by rawnsley** [comment]
[thanks for implementing this so quickly after we made the request]

After compiling from this branch I've found a couple of issues, one I think I understand and one that I don't.

Issue 1: _outBuffer_ should be _outData_ [here](https://github.com/google/filament/blob/pr/tbn/android/filament-android/src/main/cpp/VertexBuffer.cpp#L136) and [here](https://github.com/google/filament/blob/pr/tbn/android/filament-android/src/main/cpp/VertexBuffer.cpp#L149).

Issue 2: Only direct buffers are populated. If you wrap an array or use ByteBuffer.allocate then the tangent quads are not populated. The following unit tests illustrate the problem I'm seeing:

```
package com.avantis.graphics

import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.android.filament.*
import org.junit.Assert.assertArrayEquals
import org.junit.Test
import org.junit.runner.RunWith

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.FloatBuffer

@RunWith(AndroidJUnit4::class)
class FilamentLibraryTest {

    companion object {
        init {
            Filament.init()
        }
    }

    @Test
    fun packTangentFrameTest() {
        val expected = floatArrayOf(0.5f, 0.5f, 0.5f, 0.5f)
        val result = FloatArray(4)
        MathUtils.packTangentFrame(
            // Tangent
            0.0f,  1.0f, 0.0f,
            // Bitangent
            0.0f, 0.0f, -1.0f,
            // Normal
            1.0f,  0.0f,  0.0f,
            result)
        assertArrayEquals(expected, result, 0f)
    }

    @Test
    fun populateTangentQuaternionsTest() {

        // Normal vector
        val norm = floatArrayOf(1.0f, 0.0f, 0.0f)
        // Tangent vector + 1 (indicates handedness of the basis)
        val tang = floatArrayOf(0.0f, 1.0f, 0.0f, 1.0f)

        // Should match the result of packTangentFrameTest
        val expected = floatArrayOf(0.5f, 0.5f, 0.5f, 0.5f)

        // Must be allocated as direct currently or result will not be populated
        val resultBuffer = ByteBuffer.allocateDirect(16).order(ByteOrder.nativeOrder())

        val qtc = VertexBuffer.QuatTangentContext()
        qtc.quatCount = 1
        qtc.quatType = VertexBuffer.QuatType.FLOAT4
        qtc.outBuffer = resultBuffer
        qtc.normals = FloatBuffer.wrap(norm)
        qtc.tangents = FloatBuffer.wrap(tang)

        VertexBuffer.populateTangentQuaternions(qtc)

        val result = FloatArray(4)
        resultBuffer.asFloatBuffer().get(result)

        assertArrayEquals(expected, result, 0f)

    }
}
```
Swapping **allocateDirect** for **allocate** causes the test to fail as does calling **wrap** on a Java array. I may be missing something obvious or my compilation might be at fault somehow, but after a cursory glance at NioUtils.cpp, where the pointer magic happens, I can't see why the non-direct memory allocations fail.

**Comment by romainguy** [comment]
Good catch for `outBuffer` vs `outData`. @prideout make sure you fix those before submit!

**Comment by prideout** [comment]
Good catch, I amended the commit to fix the outBuffer/outData typo.  As for wrapped buffers: our buffer utility calls `ReleaseFloatArrayElements` using the JNI_ABORT flag rather than 0, which means that changes do not get committed ([doc](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html)).  I think we're probably doing this for performance reasons since Filament is almost always a consumer.  I think this could be fixed by adding a "mutable" flag to our AutoBuffer utility class, let me do that in a separate PR so that I can go ahead and submit this one.

**Comment by rawnsley** [comment]
There's another subtle problem with the norm + tangent loop in `VertexBuffer::populateTangentQuaternions`. The output pointer never moves forward because it's incremented by `ctx.outStride` (which defaults to zero) rather than `outStride` (which is correct).

It's a single line change [here](https://github.com/google/filament/blob/master/filament/src/VertexBuffer.cpp#L266).

My unit test didn't catch it because one vertex alone transforms fine, but if you transform a second vertex it overrides the result of the first.

**Comment by romainguy** [comment]
@prideout :)

**Pull request merged**
