### PR TITLE
Enable DPI awareness in Windows

### PR DESCRIPTION
**Pull request by sergeyreznik**
Since SDL source is embedded, I think this is the right place to enable high-DPI support.

### CODE REVIEW

**Comment by romainguy** [comment]
Should we update SDL2? Do newer versions support hdpi?

**Comment by sergeyreznik** [comment]
As far as I understood, high DPI in SDL used for macOS retina displays
https://wiki.libsdl.org/SDL_CreateWindow

**Comment by prideout** [comment]
As an aside, I want to mention my personal preference of GLFW over SDL if we decide to overhaul our samples framework.

GLFW has a better focus on the bare minimum for what we need, whereas SDL is a little heavier due to things like 2D rendering, audio, and joystick support.

**Comment by sergeyreznik** [comment]
@romainguy are you going to review/merge this?

**Pull request merged**
