### PR TITLE
Repair FeedbackLoops test.

### PR DESCRIPTION
**Pull request by prideout**

### CODE REVIEW

**Comment by prideout** [comment]
btw @bejado I noticed that Metal asserts `mUsedStages.empty()` but this test is a little non-standard so I'm not sure if that's a real bug or not.

**Review by romainguy — APPROVED** [review]

**Comment by bejado** [comment]
@prideout Yeah, looks like it is failing. Probably not urgent, but I'll take a look. Remind me, what are "feedback loops" used for in Filament? Some post-processing step?

**Comment by prideout** [comment]
> @prideout Yeah, looks like it is failing. Probably not urgent, but I'll take a look. Remind me, what are "feedback loops" used for in Filament? Some post-processing step?

When bloom generates a mipmap chain, it uses the same texture for reading & writing.  In GL we have to set up BASE_LEVEL and MAX_LEVEL for this work across all vendors.

Since bloom looks reasonable with Metal, I'm guessing the Metal issue has more to do with the weirdness of the test than what it's actually intended to test.  Therefore, yes totally not urgent. :)

**Comment by prideout** [comment]
@bejado never mind, I made some additional fixes to the test itself (#4152) and now the Metal assert is gone.

**Pull request merged**
