### PR TITLE
Be compatible with CMake 3.10 again

### PR DESCRIPTION
**Pull request by romainguy**
Helps with bug #2295

### CODE REVIEW

**Comment by bejado** [comment]
Can you add the change to the `filament-specific-changes.patch` file inside the `spirv-tools` dir?

**Comment by romainguy** [comment]
Will do!

**Comment by romainguy** [comment]
@bejado How did you generate that patch file?

**Comment by bejado** [comment]
The patch file is the output of `git diff`. You should be able to merge your diff with the current one via:

```
git diff | tail -n +5 >> third_party/spirv-tools/filament-specific-changes.patch
```

**Comment by romainguy** [comment]
@bejado I fixed the patch file

**Comment by bejado** [comment]
Thanks! LGTM after CI passes

**Comment by unicomp21** [comment]
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:27 (cmake_policy):
  Policy "CMP0074" is not known to this version of CMake.

**Comment by unicomp21** [comment]
^getting another cmake error

**Pull request merged**
