### PR TITLE
switch to C++17 (from C++14)

### PR DESCRIPTION
**Pull request by pixelflinger**
Some of the new features:
- no message required for `static_assert`
- nested namespace definitions, e.g.: `namespace Foo::Bar{ ... }`
- compile-time static `if`, e.g.: `if constexpr(exp) { }`
- structured binding declarations, e.g.: `auto [r, e] = foo();`
- inline variables (avoiding ODR with definitions of variables in headers)
- a file-system
- `std::optional`, `std::any`, 'std::variant`, `std::byte`
- etc ...

### CODE REVIEW

**Comment by prideout** [comment]
Windows!!!

**Comment by bejado** [comment]
Windows... :/ we might have to hold off on this until we get Filament building through GitHub Actions / VS 2019

**Comment by bejado** [comment]
Windows... :/ we might have to hold off on this until we get Filament building through GitHub Actions / VS 2019

**Comment by romainguy** [comment]
Closing PR, keeping the branch open

**Pull request closed without merging**
