### PR TITLE
GetBackendHandle() API

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by romainguy** [comment]
Thank you but those handles are a private implementation detail and should not be exposed via public APIs.

**Comment by alexey-pelykh** [comment]
True, though there are cases when access to OpenGL handle is needed outside of the filament itself 🤔

**Comment by romainguy** [comment]
Filament might not have a GL backend, we do not want to expose GL specific things.

**Comment by alexey-pelykh** [comment]
Likewise it was implemented for Vulkan as well, so it's not GL specific..

**Pull request closed without merging**
