### PR TITLE
gltfio: [extended] Fix generated color default

### LINKED ISSUE #7905: Fix for normal generation does not work for UBERSHADER in gltf_viewer app
**Describe the bug**
[Fix](https://github.com/google/filament/pull/7776) for proper normal generation does not work for UBSERSHADER.  [This](https://github.com/google/filament/discussions/7851#discussioncomment-9441128) suggestion works for JITSHADER (default in gltf_viewer.cpp sample) but it doesn't work for UBERSHADER.  Reason I want this to work for ubsershader is because we want to apply the fix for Android which only has `Ubershader.java`.  Currently the [fix](https://github.com/google/filament/pull/7776) is supported only for desktop app.

Would the possible fix for Android be creating an equivalent `Jitshader.java`?  Not sure why android only has ubershader & the benefits of one over the other.  Any help to have the fix for proper normal generation in Android would be helpful.  I tried to [apply](https://github.com/google/filament/discussions/7851#discussioncomment-9463186) the fix for Android but not working

**To Reproduce**
Run the sample `gltf_viewer.cpp` app with [this](https://github.com/google/filament/discussions/7851#discussioncomment-9441128) suggested change

**Expected behavior**
Model should appear normally with UBERSHADER
Screenshot 2024-06-04 at 11 40 36 PM

**Screenshots**
Actual behavior - Model appears all black with UBSERSHADER
Screenshot 2024-06-04 at 11 33 05 PM

**Logs**
Model:  [walls.glb.zip](https://github.com/user-attachments/files/15572949/walls.glb.zip)

**Desktop (please complete the following information):**
 - OS: Mac (reproducible in any device)
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: Metal

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

### PR DESCRIPTION
**Pull request by poweifeng**
Fixes #7905

### CODE REVIEW

**Review by pixelflinger — APPROVED** [review]

**Comment by mbalajee** [comment]
Doesn't seem to fix the [issue](https://github.com/google/filament/issues/7905).  Model (attached in the original issue) still appears all black,
Screenshot 2024-06-11 at 3 31 28 PM
@poweifeng @pixelflinger

**Comment by poweifeng** [comment]
> Doesn't seem to fix the [issue](https://github.com/google/filament/issues/7905). Model (attached in the original issue) still appears all black, Screenshot 2024-06-11 at 3 31 28 PM @poweifeng @pixelflinger

Can you attach the model again?  It seems corrupted in the previous comment.

**Comment by mbalajee** [comment]
It was attached as `.zip` cz of github attachment restriction.  Removing the `.zip` extension should work, i just tried from previous comment.

Here is the same model,
[walls.glb.zip](https://github.com/user-attachments/files/15794024/walls.glb.zip)

**Comment by poweifeng** [comment]
Let's continue the conversation in #7905.

**Comment by mbalajee** [comment]
Clean build worked.  Model appears as expected.  Thanks.

**Pull request merged**
