### PR TITLE
Include unwindows in Frustum and DriverEnums

### LINKED ISSUE #646: Cannot open include file DriverEnums.h
I tried to create a new filament Engine:
`filament::Engine* m_Engine = filament::Engine::create( );`
but I got this error:
`2>e:\brawler\external_projects\thirdparty\filament\include\filament\fence.h(24): fatal error C1083: Cannot open include file: 'filament/driver/DriverEnums.h': No such file or directory`
The folder indeed does not have DriverEnums.h, neither can I find it in the latest github branch.

### PR DESCRIPTION
**Pull request by bejado**
Fixes #646

### CODE REVIEW

**Comment by thirdmenson** [comment]
unwindows.h include also needs to be added in the math/half.h header file or I get compiler errors.

**Comment by romainguy** [comment]
half.h only includes std lib headers. It probably comes from somewhere else.

**Comment by thirdmenson** [comment]
line 185:  inline static constexpr type min() noexcept { return math::makeHalf(0x0400); }

min and max are defined in miniwindef.h so I get "non static datamember cannot be declared as iniline" error. I am able to compile fine after including unwindows.h

**Comment by romainguy** [comment]
Right but where is miniwundef.h coming from in half.h?

**Comment by thirdmenson** [comment]
Not sure but the same way miniwindef.h is coming in driverenums.h and frustum.h I guess.

**Pull request merged**
