### PR TITLE
Consider the extra entry for the directional light when rounding up the capacity

### LINKED ISSUE #665: Culler out of bounds array access
**Describe the bug**
When enabling the page heap using gflags to track down heap corruption, I noticed this out of bounds array access in ``Culler::intersects``:

image

I think the assumption that capacity is always a multiple of 8 is broken.
The data being passed in has both capacity and size of 1:

image

### PR DESCRIPTION
**Pull request by shartte**
Fixes #665

### CODE REVIEW

**Comment by shartte** [comment]
Well thinking about it again, the actual problem is the lightData resize further down and this just incidentally fixes the issue, heh.

**Comment by romainguy** [comment]
What do you mean?

**Comment by shartte** [comment]
I reworked the PR significantly and opted to split the capacity calculation for the light data and renderable lists. 
My reasoning is this: Even if the entity list is empty, there is going to be one entry in the light list that will be processed using vectorized loops. That is not true for the entity list.

**Comment by romainguy** [comment]
I haven't forgotten about this PR btw. We're just all on vacation right now :)

**Comment by shartte** [comment]
No worries, enjoy your vacations, and see you next year! 🎉

**Pull request merged**
