### PR TITLE
Swap chains are now always created with a depth buffer

### PR DESCRIPTION
**Pull request by pixelflinger**
This is to allow direct rendering of 3D objects into the swapchain 
under certain circumstances (no msaa or postprocessing).

### CODE REVIEW

**Comment by pixelflinger** [comment]
@bejado `metal` implementation is missing
@prideout `vulkan` implementation is missing
Could you add to this PR?

**Comment by prideout** [comment]
Will do.

**Comment by prideout** [comment]
It's actually quite hilarious this simple task is in Vulkan.  I will need to create a VkImage, VkImageView, and create a one-off command buffer for the sole purpose of "transitioning" the image into a depth-renderable layout.  I will get it done today though.

**Comment by prideout** [comment]
@googlebot I consent.

**Comment by bejado** [comment]
@googlebot I consent.

**Comment by prideout** [comment]
@pixelflinger  I have no idea what is going on with **cla/google**

**Comment by bejado** [comment]
Shoot, I just realized there's a bug in my Metal implementation—let me look into it before we merge this.

**Pull request merged**
