### PR TITLE
Experiment: generate AST for Settings.h

### PR DESCRIPTION
**Pull request by prideout**
This generates a JSON file that has 3.7 million lines, so I think
we'd want to parse it with a fairly efficient JSON parser!

The CMake stuff for this is pretty hacky but I wasn't able to do it
any other way.

### CODE REVIEW

**Comment by romainguy** [comment]
3.7 million lines from Settings.h? Wth. Is this because of includes?

**Comment by prideout** [comment]
> 3.7 million lines from Settings.h? Wth. Is this because of includes?

Yup it includes almost the entire Filament API.  (also, I should remove `<string>` from there)

Crazy idea:

To make it much simpler we could create a `Settings.h` in our public API, and move all our various options structs into that.  e.g. `View::BloomOptions` would be an alias for `Settings::BloomOptions`.

**Comment by romainguy** [comment]
Maybe we should just parse it and see how fast/slow it is before worrying about optimizations. I know there are good, fast JSON parsers out there.

**Comment by romainguy** [comment]
And it's not something we'll do at runtime, it can't be slower than generating our env maps through cmgen :p

**Comment by prideout** [comment]
> Maybe we should just parse it and see how fast/slow it is before worrying about optimizations. I know there are good, fast JSON parsers out there.

Yeah.  We already use jsmn for the actual serialization, which is pretty damn fast, so we could use that.  Although, it's a C/C++ library and I'm not sure if C/C++ is the right tool for codegen...  On the other hand C++ is the lingua franca...

**Comment by pixelflinger** [comment]
It's an opportunity to re-double check that we are not including things that we don't need in public headers and that we're fwd declaring everything we can.

**Pull request closed without merging**
