### PR TITLE
mipgen:  Disambiguated string with std:: prefix.

### PR DESCRIPTION
**Pull request by cubeleo**

### CODE REVIEW

**Comment by romainguy** [comment]
There's a using namespace std at the top, why is this change needed?

**Comment by cubeleo** [comment]
While the using brings "string" into the namespace, in some build environments there is another string already in the namespace and then these uses of string are ambiguous.

**Comment by prideout** [comment]
Thanks for the fix, this makes us conform to our own style:

https://github.com/google/filament/blob/master/CODE_STYLE.md#strings

**Comment by romainguy** [comment]
Thanks!

**Pull request merged**
