### PR TITLE
Add clearCoatIorChange property to materials

### PR DESCRIPTION
**Pull request by romainguy**
This property can be used to control the darkening of the base layer
due to a change in index of refraction when going through the clear
coat layer.

With `clearCoatIorChange` (left) and without (right):

screenshot_clear_coat_ior_change

### CODE REVIEW

**Comment by pixelflinger** [comment]
"clearCoatIorChange" is a very weird name.  What's a "change"? Also Ior reads like lor (I versus L) and so it looks like a typo, what's a Coatlor? is that like a Color?
Maybe use "clearCoatIndexOfRefractionAdjust"?

**Comment by romainguy** [comment]
Ior is a common abbreviation and I can't account for different fonts. It's a change in index of refraction, hence the name. Other names I could think of were just too long (like the one you propose).

**Comment by pixelflinger** [comment]
> Ior is a common abbreviation and I can't account for different fonts. It's a change in index of refraction, hence the name. Other names I could think of were just too long (like the one you propose).

It should have been IOR then -- and I think "Adjust" works better than "Change" -- i.e.: `clearCoatIORAdjust`.

**Comment by romainguy** [comment]
It would be adjustment not adjust. Then there's always the problem of acronyms in upper case vs camel case...

**Comment by pixelflinger** [comment]
> It would be adjustment not adjust. Then there's always the problem of acronyms in upper case vs camel case...

Actually, "Adjustment" is even better -- with "change" it's unclear if it's a verb. I read it like "clearCoatIorDestroy" -- i.e. a verb.

**Pull request merged**
