### PR TITLE
WIP: Add front & back stencil state

### PR DESCRIPTION
**Pull request by Michael-Lfx**
Try to address https://github.com/google/filament/issues/5659.
Could you review it? @bejado

### CODE REVIEW

**Comment by bejado** [comment]
I think we do eventually want control over the front & back stencil states, but at this time I'm not sure we want to grow `RasterState` to 128 bits. @pixelflinger any thoughts? We may need to store the stencil state elsewhere.

**Comment by romainguy** [comment]
That's a huge increase just for stencil ops. And again, SDF do *not* need this feature. Until there's a clear use case for this, we should not pay such a cost.

**Comment by pixelflinger** [comment]
> I think we do eventually want control over the front & back stencil states, but at this time I'm not sure we want to grow `RasterState` to 128 bits. @pixelflinger any thoughts? We may need to store the stencil state elsewhere.

I agree, Stencil is seldom used and it takes so much state space. Maybe we need an indirection for stencil, but I'm not sure how to do that. A related issue is that we need to compare the RasterState for auto-instancing, so I don't like it becoming even bigger.

**Comment by Michael-Lfx** [comment]
Same worry about increasing `RasterState` to 128 bits. Maybe use `uint64_t u; uint16_t v;` instead.  Again the PR is not intend to merge but just for seeking help from you. Should I push more commits?

**Comment by Michael-Lfx** [comment]
Could you take another look? @bejado @pixelflinger @romainguy

**Comment by bejado** [comment]
@Michael-Lfx We're going to hold off on this for now as we're having some internal discussions about how to best move forward with stencil state.

**Comment by pixelflinger** [comment]
we can probably close this.

**Pull request closed without merging**
