### PR TITLE
Use Frisvad's method to compute tangent space from normals-only mesh input

### PR DESCRIPTION
**Pull request by ViktorHeisenberger**
This PR introduces Frisvad's method for computing a tangent space from a normal vector for input meshes. It provides a smoother result, than the current one, having only one singularity for normals in the -Y direction.

Comparison of the current and new method:
TBN_rand_vs_frisvad

### CODE REVIEW

**Review by romainguy — APPROVED** [review]
Thank you, this looks great! Marking as approved, but I'd like confirmation from @pixelflinger and @bejado

**Review by pixelflinger — APPROVED** [review]

**Review by pixelflinger — CHANGES_REQUESTED** [review]
Looks great. Thanks!  I think this one deserves updating the `RELEASE_NOTES.md` file.

**Comment by ViktorHeisenberger** [comment]
> Looks great. Thanks! I think this one deserves updating the `RELEASE_NOTES.md` file.

Thanks! Updated in d315ec3

**Review by romainguy — APPROVED** [review]
Looks great, thank you so much!

**Pull request merged**
