### PR TITLE
enable contact-shadows functionality in mobile gltf-viewer

### PR DESCRIPTION
**Pull request by pixelflinger**
contact-shadows needs to be enabled per object.

### CODE REVIEW

**Review by prideout — APPROVED** [review]
Sure but maybe make this optional by adding `var enableContactShadows = true` similar to the other options like `recomputeBoundingBoxes`.

**Comment by pixelflinger** [comment]
> Sure but maybe make this optional by adding `var enableContactShadows = true` similar to the other options like `recomputeBoundingBoxes`.

It's not needed because contact shadows also need to be enabled on the light, and that's what we control with the checkbox in the UI.

**Comment by prideout** [comment]
> > Sure but maybe make this optional by adding `var enableContactShadows = true` similar to the other options like `recomputeBoundingBoxes`.
> 
> It's not needed because contact shadows also need to be enabled on the light, and that's what we control with the checkbox in the UI.

Ok sounds good.  (In that case I wonder why Filament's doesn't just do this automatically.)

**Comment by pixelflinger** [comment]
> > > Sure but maybe make this optional by adding `var enableContactShadows = true` similar to the other options like `recomputeBoundingBoxes`.
> > 
> > 
> > It's not needed because contact shadows also need to be enabled on the light, and that's what we control with the checkbox in the UI.
> 
> Ok sounds good. (In that case I wonder why Filament's doesn't just do this automatically.)

This is so that you *can* enable contact shadow on a per-renderable basis, since it's expensive.

**Pull request merged**
