### PR TITLE
Add test framework for libbackend

### PR DESCRIPTION
**Pull request by bejado**
This adds the ability to add unit tests for libbackend.

Tests are written in files like `test_MissingRequiredAttributes.cpp`. Tests can call driver commands and render one or more "frames" to invoke functionality. For example, the MissingRequireAttributes test checks that backends can handle shaders with vertex attributes that aren't set in a renderable.

Test runners are responsible for setting up the platform-specific environment for test cases to run. This PR adds support for macOS, and future PRs will add support for iOS, and possible Linux and Windows.

The test binary takes an `--api` flag to specify which backend API to test. The `--gtest_filter` can be used to control which test case is run (at the moment, running multiple tests causes some issues on some backends).

For example,
```
filament/backend/backend_test_mac --api opengl --gtest_filter=BackendTest.MissingRequiredAttributes
```

Right now, a test is successful if it does not crash. Perhaps in the future we could do some type of output image comparison between the backends. I've written tests for my own use when adding blitting to the Metal backend and for those, I simply visually checked the results.

I've found that developing features using this test framework is less error-prone and easier to debug—there's much less background "noise".

### CODE REVIEW

**Comment by romainguy** [comment]
There's a build failure apparently:

```
../../third_party/glslang/glslang/OSDependent/Unix/ossource.cpp:42:10: fatal error: 'semaphore.h' file not found
#include <semaphore.h>
```

LGTM otherwise.

**Comment by romainguy** [comment]
You should also add your new tests to `build/common/test_list.txt` so we run them in CI.

**Comment by bejado** [comment]
@romainguy I thought about adding them, but I'm not sure if we'll be able to create OpenGL / Metal contexts from a CI job. Worth trying, I guess.

**Comment by romainguy** [comment]
Good point. It will most likely work for metal, but GL would require swiftshader.

**Comment by bejado** [comment]
Huh, the build failure might have been a fluke.

**Pull request merged**
