### PR TITLE
Configurable buffer sizes via CMake

### PR DESCRIPTION
**Pull request by roxlu**
This feature allows us to specify the buffer sizes that are used in Allocators.h and OpenGLDriver.cpp. Quick fix for https://github.com/google/filament/issues/2057 By increasing these buffers we can render more instances.

### CODE REVIEW

**Comment by prideout** [comment]
This PR has two 1-month old commits in it, should it be rebased?

**Comment by roxlu** [comment]
> This PR has two 1-month old commits in it, should it be rebased?

I created a feature branch from upstream/master. Not sure what happened.

**Comment by romainguy** [comment]
We changed our branch from master to main a few weeks ago. And your change should define default values in the code, not just in the build system.

**Comment by roxlu** [comment]
> We changed our branch from master to main a few weeks ago. 
Ah good! I'll rebase late.

> And your change should define default values in the code, not just in the build system.

https://github.com/roxlu/filament/commit/899f9a1d1fe88c2bf54711b9af7b6e25d591e05c

What do you mean; see above for the changes in Allocators.h and OpenGLDriver.cpp

**Comment by romainguy** [comment]
That's exactly my point, your change *relies* on defines being set by the build system, not something we want. You should at least have a series of `#ifndef XXXX #define XXXX YYYY #endif`.

**Comment by roxlu** [comment]
Ah I see what you mean; I wasn’t sure if you wanted to have such an implementation. I’ll make the changes.

**Comment by romainguy** [comment]
The master branch has now been deleted to avoid further confusions. GitHub finally fixed the issue that was preventing us from getting rid of it.

**Comment by romainguy** [comment]
Your change still touches many files that are not related to your change.

**Pull request closed without merging**
