### PR TITLE
Include missing STL C++ header file.

### PR DESCRIPTION
**Pull request by syoyo**
I have tried to embed cmgen as an C++ library(i.e. not a standalone app) to an renderer application, and found some error related to missing STL C++ header files when building cmgen in such a manner with clang 6.0.1 on Linux.

Specifically, I got an undefined error of `condition_variable` and `memcpy` definition.

Here is an CMakeLists.txt fragment to reproduce an issue

```
  set(FILAMENT_TOOLS_SOURCE
      #${CMAKE_SOURCE_DIR}/third_party/filament/tools/cmgen/src/cmgen.cpp
      ${CMAKE_SOURCE_DIR}/third_party/filament/tools/cmgen/src/Cubemap.cpp
      ${CMAKE_SOURCE_DIR}/third_party/filament/tools/cmgen/src/CubemapIBL.cpp
      ${CMAKE_SOURCE_DIR}/third_party/filament/tools/cmgen/src/CubemapSH.cpp
      ${CMAKE_SOURCE_DIR}/third_party/filament/tools/cmgen/src/CubemapUtils.cpp
      ${CMAKE_SOURCE_DIR}/third_party/filament/tools/cmgen/src/Image.cpp
      ${CMAKE_SOURCE_DIR}/third_party/filament/tools/cmgen/src/JobQueue.cpp
      ${CMAKE_SOURCE_DIR}/third_party/filament/tools/cmgen/src/ProgressUpdater.cpp
  )

  add_library(filament_tool ${FILAMENT_TOOLS_SOURCE})

  target_include_directories(filament_tool PRIVATE ${CMAKE_SOURCE_DIR}/third_party/filament/libs/math/include
                                                   ${CMAKE_SOURCE_DIR}/third_party/filament/libs/image/include
                                                   ${CMAKE_SOURCE_DIR}/third_party/filament/libs/utils/include
                                                   ${CMAKE_SOURCE_DIR}/third_party/filament/libs/imageio/include)

...

# Add filament_tool to your target
target_link_libraries(myapp filament_tool)
```

### CODE REVIEW

**Comment by syoyo** [comment]
@romainguy Changes are trivial, thus you can fix an issue on your side and discard this PR

**Comment by romainguy** [comment]
I'm happy to approve the PR, all you have to do is click the link above to sign the CLA.

**Comment by syoyo** [comment]
@romainguy CLA is too much for this PR. If required, I can open an github issue instead of PR.

**Comment by syoyo** [comment]
Thanks!

**Pull request closed without merging**
