### PR TITLE
getSkinCount / getJoints / getSkinTargets API

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@googlebot I fixed it.

**Comment by FabianRueckert** [comment]
@googlebot I fixed it.

**Comment by FabianRueckert** [comment]
@googlebot I consent.

**Review by romainguy — COMMENTED** [review]
What is the purpose of this API?

**Comment by alexey-pelykh** [comment]
@romainguy to be able to mirror ex-Sceneform scenegraph with Filament

**Comment by prideout** [comment]
It should be possible to sync with an outside system using `FilamentAsset::getEntities()` and/or `FilamentAsset::getSourceAsset()`.

**Comment by alexey-pelykh** [comment]
@prideout how to get only joints from `getEntities()` list? Using `getSourceAsset` in Android is impossible in any case, and that's as backdoor-ish badly as it can get

**Pull request closed without merging**
