### PR TITLE
Add support for KHR_materials_volume

### PR DESCRIPTION
**Pull request by romainguy**
Adds support for `KHR_materials_volume` to `gltfio`. It is important to note that we don't currently handle the special
case of thickness set to 0 which requires to change the refraction model to a thin model. We do however — thanks to a
fairly gross hack — handle thickness scaling.

Screen Shot 2021-07-09 at 4 58 11 PM

This PR also addresses rendering issues with transmission, most notably by using alpha-as-coverage instead of the fade blending mode.

Screen Shot 2021-07-09 at 7 04 25 PM

### CODE REVIEW

**Review by pixelflinger — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Will there be a support for MaterialProvider in Android?

**Comment by romainguy** [comment]
@alexey-pelykh How so? This extension is handled by gltfio so it will work on Android.

**Comment by alexey-pelykh** [comment]
@romainguy but it's not exposed in `MaterialProvider.MaterialKey`?

**Comment by romainguy** [comment]
Ah you're right, that's an oversight. I'll fix it.

**Pull request merged**
