### PR TITLE
Fix, potential null dereferences in OpenGLProgram

### LINKED ISSUE #5059: Compute morphing on GPU #4999 breaks bones
hi,

#4999 breaks renderables with bones
`samplerBindings` has nullptr entries, which crashes when accessed later:
https://github.com/google/filament/blob/8d1402d37b0b87cc64ef64550b1f000b9b0a16fd/filament/backend/src/opengl/OpenGLProgram.cpp#L274

I can reproduce it with opengl backend on windows with unmodified `gltf_viewer` and an animated model from gltf sample repro, such as [BrainStem.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BrainStem/glTF-Embedded/BrainStem.gltf)

### PR DESCRIPTION
**Pull request by daemyung**
Morphing is enabled but no morph targets in some models.

Fixes #5059

### CODE REVIEW

**Review by pixelflinger — COMMENTED** [review]
I don't think we should log anything here. Isn't this case completely normal?

**Comment by daemyung** [comment]
> I don't think we should log anything here. Isn't this case completely normal?

Metal backend prints logs in this case. So I print logs at here. If you still want to remove log, please let me know.
Now it's normal behavior. Because `morphing_targets` is required even if only skinning is enabled. So texture can be null.

**Comment by pixelflinger** [comment]
> > I don't think we should log anything here. Isn't this case completely normal?
> 
> Metal backend prints logs in this case. So I print logs at here. If you still want to remove log, please let me know. Now it's normal behavior. Because `morphing_targets` is required even if only skinning is enabled. So texture can be null.

Yes, I think we need to remove the logs for normal behavior, i.e.: if there are no mistake from the user. You can leave a comment instead.

Thanks!

**Comment by daemyung** [comment]
> > > I don't think we should log anything here. Isn't this case completely normal?
> > 
> > 
> > Metal backend prints logs in this case. So I print logs at here. If you still want to remove log, please let me know. Now it's normal behavior. Because `morphing_targets` is required even if only skinning is enabled. So texture can be null.
> 
> Yes, I think we need to remove the logs for normal behavior, i.e.: if there are no mistake from the user. You can leave a comment instead.
> 
> Thanks!

Yes I was wrong. There is no log in `MetalDriver` for no binding sampler groups. I removed it.

**Comment by daemyung** [comment]
@pixelflinger BTW you don't have to review my code on your weekend. Actually it's my personality... I can't stand anything to do. You can deserve your weekend.

**Review by pixelflinger — APPROVED** [review]

**Pull request merged**
