### PR TITLE
Add Android sample app

### PR DESCRIPTION
**Pull request by romainguy**
It’s a simple rotating triangle but provides a good overview of how to use Filament on Android.

As requested in #29

### CODE REVIEW

**Comment by prideout** [comment]
Kotlin FTW !!! :)

**Comment by romainguy** [comment]
Good catch, I didn't even notice those files. They wouldn't work anyway since I removed test dependencies from the Gradle file.

**Comment by prideout** [comment]
I don't see any `build.sh` or `CMakeLists` changes here, which might be intentional but I wanted to mention that just in case.

**Comment by romainguy** [comment]
You must currently open the sample in Android Studio to build it. I'm not sure yet how I want to handle Android samples in regular builds. They can be slow to compile. Maybe with a new flag in build.sh?

**Pull request merged**
