### PR TITLE
Add scripts for combining static libraries

### PR DESCRIPTION
**Pull request by bejado**
These scripts will be used to generate a single `filamat` static library installed into the `dist/lib/<arch>` folder. Doing so makes it much simpler for clients to use the library (as opposed to having to link against a bunch of glslang and SPIRV-Cross dependencies). It also makes the Android AAR Gradle file more succinct.

### CODE REVIEW

**Comment by romainguy** [comment]
Can you put those scripts in build/ please? (In whatever subdirectory makes sense)

**Comment by prideout** [comment]
@bejado We might need to (eventually) enhance this script to support macOS Universal Binaries.

Our build breaks right now if you try to do `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`, and I think this script is the only breaking point.

I'm not exactly sure how to support this, but I think it would involve using the `lipo` tool to extract all arches and recombine them.

**Comment by bejado** [comment]
@prideout Yes, macOS universal binaries are on my list to look into. Instead of this script though, I think the [`create-universal-libs.sh`](https://github.com/google/filament/blob/main/build/ios/create-universal-libs.sh) script is closer to what we want. Its a wrapper around the `lipo` tool.

What led you to needing to set `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`?

**Comment by prideout** [comment]
@bejado Oh nice, that sounds like the right course!

I bought myself an M1 for personal use, and was playing around.  :)

**Pull request merged**
