### PR TITLE
Update cgltf to version 1.13

### PR DESCRIPTION
**Pull request by daemyung**

### CODE REVIEW

**Comment by daemyung** [comment]
I think this PR does not require to warrant a release note.

**Comment by romainguy** [comment]
I’m not against upgrading but it’s a bit useless if we don’t implement support for the new extensions…

**Comment by daemyung** [comment]
@romainguy Yes... Honestly this upgrade is needed for me. I need to re-write GLTF and GLB in some reasons and there is some bugs in current cgltf in filament. So I hope to accept this PR if there is no regression issues.

**Review by bejado — APPROVED** [review]

**Comment by romainguy** [comment]
@daemyung Sure, but why are you using the version of cgltf that comes with Filament and not your own? `third_party` libraries are not part of our public API.

**Comment by daemyung** [comment]
@romainguy Yes I can do that and technically you are write. I just don't want to increase more dependencies on the current project.

@bejado Thanks!

**Pull request merged**
