### PR TITLE
gltfio: enable specular AO to "fix" #1870

### PR DESCRIPTION
**Pull request by prideout**

### CODE REVIEW

**Comment by prideout** [comment]
Sorry I haven't answered your question yet, I need to take a look at the lighting math used by Three and Babylon.

**Comment by romainguy** [comment]
Wait, did you confirm that's the right fix? Do other engines apply AO to the specular term? This is not what this feature does. It computes a different AO term for specular based on the diffuse AO term but it's not the same value.

**Comment by prideout** [comment]
Doh!   I'll revert this since it needs further investigation.

**Comment by prideout** [comment]
Reverted on master.

**Comment by prideout** [comment]
Ok, I think we can re-merge this PR, based on this finding in ThreeJS:

```
reflectedLight.indirectSpecular *= computeSpecularOcclusion( dotNV, ambientOcclusion, material.specularRoughness );
```

The `ambientOcclusion` term in the above snippet seems to be a simple diffuse AO quantity:

```
float ambientOcclusion = ( texture2D( aoMap, vUv2 ).r - 1.0 ) * aoMapIntensity + 1.0;
```

Oh, and their implementation of `computeSpecularOcclusion` looks ours except that they clamp it.

What do you think Romain?  Apologies for my trigger happiness.

**Comment by romainguy** [comment]
SG then! I wish this was part of the spec…

**Pull request merged**
