### PR TITLE
Add hello-ar iOS sample

### PR DESCRIPTION
**Pull request by bejado**
This adds a new iOS sample, hello-ar, that demonstrates camera streaming through external images and ARKit.

The most important bits are in:
- `FilamentArViewController`
- `FilamentApp`
- `FullScreenTriangle`
- `MathHelpers.h`

Most everything else is boilerplate from previous samples.

hello-ar

Shadows coming soon!

### CODE REVIEW

**Comment by Realitian** [comment]
Hi, @bejado 
Thanks for adding iOS AR example.
btw, how can make it work in portrait mode?
Actually, I tried to run it in portrait mode (my all UI made in portrait mode), but example was landscape right mode.
I couldn't setup the matrix in portrait mode.
I tried to change camera.transform with [camera viewMatrixForOrientation:UIInterfaceOrientationPortrait], but the object wasn't be stable.
Can you give me any idea?
Thank in advance!

**Comment by House3D** [comment]
Hello @bejado
Are the shadows done for this examples?

**Comment by bejado** [comment]
> Hello @bejado
> 
> Are the shadows done for this example?

Yes, the latest version of this sample has shadows.

**Comment by Stefterv** [comment]
> Hi, @bejado
> Thanks for adding iOS AR example.
> btw, how can make it work in portrait mode?
> Actually, I tried to run it in portrait mode (my all UI made in portrait mode), but example was landscape right mode.
> I couldn't setup the matrix in portrait mode.
> I tried to change camera.transform with [camera viewMatrixForOrientation:UIInterfaceOrientationPortrait], but the object wasn't be stable.
> Can you give me any idea?
> Thank in advance!

I ran into the same issue, I've fixed it with the following
`
let projection = frame.camera.projectionMatrix(for: orientation, viewportSize: self.view.frame.size, zNear: 0.01, zFar: 10.00);
`
`
let transform = frame.camera.viewMatrix(for: orientation).inverse;
`

And with the current orientation grabbed this way:
`
    override func willRotate(to toInterfaceOrientation: UIInterfaceOrientation, duration: TimeInterval) {
        orientation = toInterfaceOrientation;
    }
`

**Pull request merged**
