### PR TITLE
added travis CI build

### PR DESCRIPTION
**Pull request by udnaan**
This adds a simple build using [Travis CI](https://travis-ci.org/).

For now it only performs a build using docker/ubuntu:18.04 image but it should be trivial to run tests as part of the build.

### CODE REVIEW

**Comment by romainguy** [comment]
Thanks for the contribution but we already have a continuous integration in place. You can see it in every PR with the 3 labels ci/linux, ci/android and ci/mac. We're working on the Windows build.

**Comment by udnaan** [comment]
Fair enough. Closing.

**Comment by udnaan** [comment]
Could it be CI Rivalry?

**Comment by romainguy** [comment]
Looks like our CI builds can only be triggered when the author of a change is an owner of this repository. I just pushed a config change that will hopefully fix that.

**Pull request closed without merging**
