### PR TITLE
delete list_licenses

### PR DESCRIPTION
**Pull request by ccworld1000**
delete list_licenses

### CODE REVIEW

**Comment by pixelflinger** [comment]
Can we get more context please?

**Comment by ccworld1000** [comment]
syntax error @pixelflinger

**Comment by romainguy** [comment]
It's not necessary anymore but perfectly valid even in CMake 3.25. https://cmake.org/cmake/help/latest/command/endfunction.html

We can take the change there's no downside to it though. It should trigger a syntax error though (and doesn't for us?)

**Comment by pixelflinger** [comment]
@ccworld1000 you need to sign the CLA for us to be able to commit the change.

**Comment by ccworld1000** [comment]
Due to some restrictions or special reasons, I cannot access the "CLA" association.
You can help me handle it manually or turn off the changes directly.

@pixelflinger

**Comment by pixelflinger** [comment]
closing, will be handled by #6384

**Pull request closed without merging**
