### PR TITLE
Fix build errors caused by deprecated enums on macOS

### PR DESCRIPTION
**Pull request by daemyung**

### CODE REVIEW

**Comment by daemyung** [comment]
@romainguy How's about this approch?

**Comment by bejado** [comment]
What is the value of `CMAKE_OSX_DEPLOYMENT_TARGET` inside your `CMakeCache.txt`? It should be 10.15. I'm not sure how you'd be seeing the errors you mentioned in #6580 unless that was set to 13.0.

**Comment by daemyung** [comment]
@bejado `CMAKE_OSX_DEPLOYMENT_TARGET` is empty.

```
//Minimum OS X version to target for deployment (at runtime); newer
// APIs weak linked. Set to empty string for default value.
CMAKE_OSX_DEPLOYMENT_TARGET:STRING=
``
`

**Comment by bejado** [comment]
@daemyung Try setting it to `10.15`. It should be getting set to 10.15 in our [build.sh script here](https://github.com/google/filament/blob/29983772edfddf0ed2ebf29ab1c3e198c4a749e8/build.sh#L215-L223).

**Comment by daemyung** [comment]
@bejado It's fine now. Do you want to close this PR? I think it's worth to merge.

**Comment by bejado** [comment]
@daemyung I'd prefer not to have unnecessary`#if` checks.

**Pull request closed without merging**
