### PR TITLE
fix macos openggl compile process_ARB_shading_language_packing type c…

### PR DESCRIPTION
**Pull request by mirsfang**
fix macos compile shader error is :

ERROR: 0:9: Types 'unsigned int' and 'int' in conditional operator do not match (and no applicable implicit type conversion)\n
ERROR: 0:10: Use of undeclared identifier 'nz'

### CODE REVIEW

**Comment by mirsfang** [comment]
For next branch cut* header

**Comment by mirsfang** [comment]
how to add label?

**Review by bejado — APPROVED** [review]

**Review by pixelflinger — APPROVED** [review]

**Comment by pixelflinger** [comment]
Is this a new error? I'm using macOS and never ran into it?

**Comment by mirsfang** [comment]
I used this shader for other projects when compiling glsl with 330core version

**Pull request merged**
