### PR TITLE
Make DriverAPI.inc work with MSVC19

### PR DESCRIPTION
**Pull request by pixelflinger**
@greg7mdp hopefully this works! could you try this change?

### CODE REVIEW

**Comment by greg7mdp** [comment]
Unfortunately it is not building with msvc:

image

**Comment by pixelflinger** [comment]
@greg7mdp alright, I've updated the PR, I think this should work now

**Comment by greg7mdp** [comment]
@pixelflinger YES, this version builds fine, awesome!
After you merge it I'll pull it in my branch and remove the duplicated file .inc/msvc.

**Comment by greg7mdp** [comment]
@pixelflinger, this is merged in my branch, thanks again!

**Pull request merged**
