### PR TITLE
break dependency on libutils

### PR DESCRIPTION
**Pull request by pixelflinger**
it was only used of Path which now can be replaced bu
std::filesystem::path.

### CODE REVIEW

**Comment by pixelflinger** [comment]
Looks like iOS does't have std::filesystem before 10.15

**Comment by bejado** [comment]
I think we could move off of macOS 10.14 if that's the only requirement blocking this.

**Comment by romainguy** [comment]
Do we have 10.15 in CI?

**Comment by bejado** [comment]
Yes, `macos-latest` is 10.15.

**Pull request closed without merging**
